# .github/workflows/ci.yml
name: Java CI with Maven + Postman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build & Test
        run: mvn -B verify

      - name: Start Spring Boot App
        run: |
          echo "Starting Spring Boot with H2..."
          nohup mvn spring-boot:run > app.log 2>&1 &
          echo "App started in background"

          # Show live logs
          tail -f app.log &
          LOG_PID=$!

          # Wait for health endpoint (max 2 minutes)
          echo "Waiting for http://localhost:8080/actuator/health ..."
          for i in {1..60}; do
            if curl -f http://localhost:8080/actuator/health > /dev/null 2>&1; then
              echo "App is UP!"
              kill $LOG_PID 2>/dev/null || true
              exit 0
            fi
            echo "Still waiting... ($i/60)"
            sleep 2
          done

          echo "App failed to start!"
          kill $LOG_PID 2>/dev/null || true
          cat app.log
          exit 1

      - name: Install Newman
        run: |
          npm config set fund false
          npm install -g newman

      - name: Verify Collection Exists
        run: |
          echo "=== postman/ folder contents ==="
          ls -la postman/
          echo "Collection size:"
          wc -c postman/Spring_api_test.postman_collection.json

      - name: Run Postman API Tests
        env:
          BASE_URL: http://localhost:8080
        run: |
          newman run "postman/Spring_api_test.postman_collection.json" \
            --env-var base_url=$BASE_URL \
            --reporters cli,junit \
            --reporter-junit-export newman-report.xml

      - name: Upload Postman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: newman-report.xml

      - name: Upload App Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: app-log
          path: app.log